--- 
- hosts: localhost
  connection: local
  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "ansible-instance11"
      key_name: "ec2keypair"
      vpc_subnet_id: subnet-0ea729f85104f447f
      instance_type: t2.micro
      security_group: default
      region: us-east-2
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: ami-0862be96e41dcbf74
      tags:
        Environment: Testing



